export default interface Comment {
    total_awards_received: number;
    approved_at_utc: number;
    ups: number;
    awarders: any;
    mod_reason_by: null
    banned_by: null
    author_flair_type: string;
    removal_reason: null
    link_id: string;
    author_flair_template_id: null
    likes: boolean;
    replies: any;
    user_reports: []
    saved: false
    id: string;
    banned_at_utc: null
    mod_reason_title: null
    gilded: number;
    archived: false
    no_follow: false
    author: string;
    can_mod_post: false
    send_replies: true
    parent_id: string;
    score: number;
    author_fullname: string;
    report_reasons: null
    approved_by: null
    all_awardings: []
    subreddit_id: string;
    body: string;
    edited: false
    author_flair_css_class: null
    is_submitter: false
    downs: number;
    author_flair_richtext: []
    author_patreon_flair: false
    body_html: string;
    gildings: {}
    collapsed_reason: null
    associated_award: null
    stickied: false
    author_premium: false
    subreddit_type: string;
    can_gild: true
    subreddit: string;
    author_flair_text_color: null
    score_hidden: false
    permalink: string;
    num_reports: null
    locked: false
    name: string;
    created: number;
    author_flair_text: null
    collapsed: false
    created_utc: 1580839724
    subreddit_name_prefixed: string;
    controversiality: number;
    depth: number;
    author_flair_background_color: null
    collapsed_because_crowd_control: null
    mod_reports: []
    mod_note: null
    distinguished: null
}